function spm_TOM8
% TOM8 Toolbox wrapper to call TOM8 functions
%_______________________________________________________________________
% Christian Gaser
% $Id: spm_TOM8.m 7 2009-09-30 14:25:20Z gaser $

rev = '$Rev: 167 $';

SPMid = spm('FnBanner',mfilename,rev);
[Finter,Fgraph,CmdLine] = spm('FnUIsetup','Template-O-Matic');
spm_help('!ContextHelp',mfilename);
spm_help('!Disp','TOM8.man','',Fgraph,'      Template-O-Matic toolbox for SPM8');

fig = spm_figure('GetWin','Interactive');
h0  = uimenu(fig,...
	'Label',	'TOM8',...
	'Separator',	'on',...
	'Tag',		'TOM8',...
	'HandleVisibility','on');
h1  = uimenu(h0,...
	'Label',	'Estimate regression parameters',...
	'Separator',	'off',...
	'Tag',		'Estimate regression parameters',...
	'CallBack','spm_jobman(''interactive'','''',''spm.tools.tom.estimate'');',...
	'HandleVisibility','on');
h2  = uimenu(h0,...
	'Label',	'Create new template',...
	'Separator',	'off',...
	'Tag',		'Create new template',...
	'CallBack','spm_jobman(''interactive'','''',''spm.tools.tom.create'');',...
	'HandleVisibility','on');
h3  = uimenu(h0,...
	'Label',	'Print information about TOM.mat',...
	'Separator',	'off',...
	'Tag',		'Print information about TOM.mat',...
	'CallBack','spm_jobman(''interactive'','''',''spm.tools.tom.getinfo'');',...
	'HandleVisibility','on');
h4  = uimenu(h0,...
	'Label',	'Check for updates',...
	'Separator',	'off',...
	'Tag',		'Check for updates',...
	'CallBack','cg_tom8_update(1);',...
	'HandleVisibility','on');
